services:
    phpbbde.newsletter.listener:
        class: phpbbde\newsletter\event\listener
        arguments:
            - '@config'
            - '@log'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%tables.users%'
        tags:
            - { name: event.listener }
